# Admin Ping
GET {{BASEURL}}/admin/ping
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjgxMzc3MTcwLCJzdWIiOiIxMzk3MzU4Yi0zNmYwLTQzNDgtYmM4ZC04YTIyZGNkYzVlYjMiLCJlbWFpbCI6ImFjdGl2aXR5LnNjaG9vbHNoMkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX2NvbmZpcm0iOnRydWUsImVtcGxveWVlQ29kZSI6IkVXVkpXQmNYY1hkc2VydmRmdnRyYnIxIiwiZmlyc3ROYW1lIjoiU2hpdmFtIiwibGFzdE5hbWUiOiJTYWhpbCIsIm9yZ0FkbWluIjp0cnVlLCJvcmdDb2RlIjoiIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2ODEzNzM1NzB9XSwic2Vzc2lvbl9pZCI6Ijg1ODNiZDcwLTU4OTMtNGYwNS1hODI0LTNmYjFhNWVmNzUxMyJ9.C4uCwwAUQolf6Fw1zhJtNBqGoegkXOXyUZrBifMXNKo
