# Admin Ping
GET {{BASEURL}}/admin/ping
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer {{BEARER_TOKEN}}


### Generate Magic Link
GET {{BASEURL}}/admin/generate-magic-link
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer {{BEARER_TOKEN}}
