# Admin Ping
GET {{BASEURL}}/admin/ping
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer {{BEARER_TOKEN}}


### Generate Magic Link
GET {{BASEURL}}/admin/generate-magic-link
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer {{BEARER_TOKEN}}

### Get Pending Magic Link
GET {{BASEURL}}/admin/get-pending-magic-links
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer {{BEARER_TOKEN}}

### Revoke Pending Magic Link by ID
GET {{BASEURL}}/admin/revoke-pending-magic-link?employeeCode=38d6ded8-1329-4416-a775-686be9cad161
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer {{BEARER_TOKEN}}

### Request All Org Accesses
GET {{BASEURL}}/admin/get-all-accesses
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer {{BEARER_TOKEN}}

### Add Access to Org
POST {{BASEURL}}/admin/add-access-to-org
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}
Authorization: bearer {{BEARER_TOKEN}}

{
    "payload": [
                    {
                        "primaryCategory":"Software",
                        "secondaryCategory": "GSuite",
                        "description":"G Suite is a cloud-based productivity suite designed and developed by Google. It includes a range of powerful and collaborative tools such as Gmail, Google Drive, Google Docs, Google Sheets, Google Slides, and Google Forms."
                    }
                ]
}
