@BASEURL=https://wandering-shorts-deer.cyclic.app


POST {{BASEURL}}/auth/login
Content-Type: application/json

{
    "email":"activity.schoolsh2@gmail.com",
    "password":"TestPassword123"
}

###

GET {{BASEURL}}/open/ping