
# Login User to the Service
POST {{BASEURL}}/auth/login
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}

{
    "email":"{{EMAIL}}",
    "password":"{{PASSWORD}}"
}

###

# SignUp User to the Service
POST {{BASEURL}}/auth/individual-signup
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}

{
    "firstName":"Shivam",
    "lastName":"Sahil",
    "emailAddress":"{{EMAIL}}",
    "orgCode":"{{ORG_CODE}}",
    "employeeCode": "{{EMPLOYEE_CODE}}",
    "securePassword": "{{PASSWORD}}"
}

###
# SignUp Admin to the Service
POST {{BASEURL}}/auth/org-admin-signup
Content-Type: application/json
x-wix-api-key: {{WIX_BACKEND_API_KEY}}

{
    "firstName":"Shivam",
    "lastName":"Sahil",
    "emailAddress":"{{EMAIL}}",
    "orgCode":"{{ORG_CODE}}",
    "employeeCode": "{{EMPLOYEE_CODE}}",
    "securePassword": "{{PASSWORD}}",
    "isAdmin": true
}

###

# Check if Service is Up and Running
GET {{BASEURL}}/open/ping